# Generated by Django 5.2 on 2025-04-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("posicion", models.CharField(max_length=50)),
                ("estatura", models.FloatField()),
                ("peso", models.FloatField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="jugadores_fotos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticasJuego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("pase_corto", models.IntegerField(default=0)),
                ("pase_largo", models.IntegerField(default=0)),
                ("control", models.IntegerField(default=0)),
                ("conducciones", models.IntegerField(default=0)),
                ("remate", models.IntegerField(default=0)),
                ("regate", models.IntegerField(default=0)),
                ("juego_aereo", models.IntegerField(default=0)),
                ("vision", models.IntegerField(default=0)),
                ("concentracion", models.IntegerField(default=0)),
                ("ritmo_intensidad", models.IntegerField(default=0)),
                ("duelos_ofensivos", models.IntegerField(default=0)),
                ("duelos_defensivos", models.IntegerField(default=0)),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jugadores.jugador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticasGenerales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("td_puesto", models.IntegerField(default=0)),
                ("td_otros_puestos", models.IntegerField(default=0)),
                ("ejecucion", models.IntegerField(default=0)),
                ("m_defensa", models.IntegerField(default=0)),
                ("m_ofensivo", models.IntegerField(default=0)),
                ("pph", models.IntegerField(default=0)),
                ("ppi", models.IntegerField(default=0)),
                ("rph", models.IntegerField(default=0)),
                ("rpi", models.IntegerField(default=0)),
                ("jcabeza", models.IntegerField(default=0)),
                ("conduccion", models.IntegerField(default=0)),
                ("controles", models.IntegerField(default=0)),
                ("finta_regate", models.IntegerField(default=0)),
                ("agilidad", models.IntegerField(default=0)),
                ("velocidad", models.IntegerField(default=0)),
                ("resistencia", models.IntegerField(default=0)),
                ("fuerza", models.IntegerField(default=0)),
                ("flexibilidad", models.IntegerField(default=0)),
                ("cpsi", models.IntegerField(default=0)),
                ("ccog", models.IntegerField(default=0)),
                ("crel", models.IntegerField(default=0)),
                ("ccomp", models.IntegerField(default=0)),
                ("criv", models.IntegerField(default=0)),
                ("disci", models.IntegerField(default=0)),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jugadores.jugador",
                    ),
                ),
            ],
        ),
    ]
