# Generated by Django 5.2 on 2025-04-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jugadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugador",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
