# Generated by Django 5.2 on 2025-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jugadores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jugador",
            name="posicion",
            field=models.CharField(
                choices=[
                    ("ARQ", "Arquero"),
                    ("LTD", "Lateral Derecho"),
                    ("LTI", "Lateral Izquierdo"),
                    ("DFC", "Defensa Central"),
                    ("MCD", "Mediocampista Defensivo"),
                    ("MC", "Mediocampista Central"),
                    ("MCO", "Mediocampista Ofensivo"),
                    ("EXD", "Extremo Derecho"),
                    ("EXI", "Extremo Izquierdo"),
                    ("DEL", "Delantero Centro"),
                    ("SD", "Segundo Delantero"),
                    ("MP", "Mediapunta"),
                ],
                max_length=3,
            ),
        ),
    ]
