from .graficos import crear_grafico_radar_juego, crear_grafico_radar_generales
from .pdf_individual import generar_pdf_jugador
from .excel_report import generar_excel_jugador
from .comparativo_pdf import generar_comparativo_pdf