# Generated by Django 5.2 on 2025-04-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "posicion",
                    models.CharField(
                        choices=[
                            ("ARQ", "Arquero"),
                            ("LTD", "Lateral Derecho"),
                            ("LTI", "Lateral Izquierdo"),
                            ("DFC", "Defensa Central"),
                            ("MCD", "Mediocampista Defensivo"),
                            ("MC", "Mediocampista Central"),
                            ("MCO", "Mediocampista Ofensivo"),
                            ("EXD", "Extremo Derecho"),
                            ("EXI", "Extremo Izquierdo"),
                            ("DEL", "Delantero Centro"),
                            ("SD", "Segundo Delantero"),
                            ("MP", "Mediapunta"),
                        ],
                        max_length=3,
                    ),
                ),
                ("estatura", models.FloatField()),
                ("peso", models.FloatField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="jugadores_fotos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticasJuego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("pase_corto", models.FloatField(default=0)),
                ("pase_largo", models.FloatField(default=0)),
                ("pase_efectivo", models.FloatField(default=0)),
                ("pase_errado", models.FloatField(default=0)),
                ("control", models.FloatField(default=0)),
                ("conducciones", models.FloatField(default=0)),
                ("remate", models.FloatField(default=0)),
                ("regate", models.FloatField(default=0)),
                ("juego_aereo", models.FloatField(default=0)),
                ("vision", models.FloatField(default=0)),
                ("concentracion", models.FloatField(default=0)),
                ("ritmo_intensidad", models.FloatField(default=0)),
                ("duelos_ofensivos", models.FloatField(default=0)),
                ("duelos_defensivos", models.FloatField(default=0)),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jugadores.jugador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticasGenerales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("td_puesto", models.FloatField(default=0)),
                ("td_otros_puestos", models.FloatField(default=0)),
                ("ejecucion", models.FloatField(default=0)),
                ("m_defensa", models.FloatField(default=0)),
                ("m_ofensivo", models.FloatField(default=0)),
                ("pph", models.FloatField(default=0)),
                ("ppi", models.FloatField(default=0)),
                ("rph", models.FloatField(default=0)),
                ("rpi", models.FloatField(default=0)),
                ("jcabeza", models.FloatField(default=0)),
                ("conduccion", models.FloatField(default=0)),
                ("controles", models.FloatField(default=0)),
                ("finta_regate", models.FloatField(default=0)),
                ("agilidad", models.FloatField(default=0)),
                ("velocidad", models.FloatField(default=0)),
                ("resistencia", models.FloatField(default=0)),
                ("fuerza", models.FloatField(default=0)),
                ("flexibilidad", models.FloatField(default=0)),
                ("cpsi", models.FloatField(default=0)),
                ("ccog", models.FloatField(default=0)),
                ("crel", models.FloatField(default=0)),
                ("ccomp", models.FloatField(default=0)),
                ("criv", models.FloatField(default=0)),
                ("disci", models.FloatField(default=0)),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jugadores.jugador",
                    ),
                ),
            ],
        ),
    ]
